print('      /^\/^\\')
print('     _|__| O|')
print('\/   /~   \_/\\')
print('\_____|____________/\\')
print('    \________  \\')
print('        `\  \         \\')
print('         |  |        \\')
print('         /  /         \\')
print('        /  /         \\\\')
print('       /  /          \  \\')
print('      /  /           \   \\')
print('     /  /      _----_     \   \\')
print('    /  /      _-~    ~-_   |  |')
print('   (  (     _-~ _--_  ~-_    _/   |')
print('    \   ~-_____-~ _-~   ~- _ ~-_-~  /')
print('     ~-_      _-~     ~-_    _-~')
print('       ~--______-~         ~-___-~') 

input('Press enter to continue...')